### ISSUE TITLE
TOPの余計なアイテムを削除

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#12]
・カレーは飲み物じゃない
・エレキ、アコギなどをクリックすると抽出して表示する機能、いるううう？→イラン戦争勃発。

**Comment by yuu-eguci** [comment]
何かを削除する絵文字は 🔥 ！
README に、絵文字についての情報を追加しました！

https://github.com/yuu-eguci/pari-yo-jana-924#%EF%B8%8F-commit-message-with-emoji-%E8%A9%A6%E7%94%A8%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA

**Comment by yuu-eguci** [comment]
この issue の内容、すでにコミット済みだと思います。

- トップに「飲み物」テキストがもう無い。
- ギャラリーももう無い。

Close しますねー。
