### ISSUE TITLE
🚧 コピーライトのターゲット絞る

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#13]
・10万円台でオーダーができる、その訳
・どんな客がターゲットか（Swordは売り出したいけど球数すくなすぎる。
・どんなお店なのか（オーダーメインなのか、買取なのか販売なのか）

**Comment by onsentawake** [comment]
最終的にブラッシュアップしたいので、全体決まったらもう一度コピーライトを考えます。
デプロイ前の最終調整

**Comment by yuu-eguci** [comment]
Closed by #59
