### ISSUE TITLE
スマホ画面のメニューの一番上に「トップへ戻るボタン」ほしいかも

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#20]

**Comment by yuu-eguci** [comment]
about3.html にはあります。

![comment](https://user-images.githubusercontent.com/28250432/93408104-b57c6000-f8ce-11ea-840e-5a5d87d301d3.png)

他のページに適用するときはご参考に。

**Comment by onsentawake** [comment]
あ、そういう意味だったのですね～　これはすぐできそうです
意味合いとしては、トップへ戻るボタンをスマホの時だけ表示させるという意味だと思っていたので、
これでOKならもう迷わなくて済みますｗ

ではこれもクローズ！DNBD

**Comment by yuu-eguci** [comment]
現在では広くても狭くても表示されてます。
狭いときだけ表示することは可能です。そのほうがよければそれも出来ますが、どうします? > やるなら reopen issue

**Comment by onsentawake** [comment]
jiffwatson did not reopened its issue

**Comment by yuu-eguci** [comment]
Jiff cannot reopen his own issue ってこと?

**Comment by onsentawake** [comment]
彼は問題を再開しません。
なぜならばそれは問題ではありません。
彼は簡単に考えます。その問題を。

ということで、やらなくてよいならそのまんまにしたいでーす！！
これは使いこなしたらとてつもなく便利になりそう

**Comment by yuu-eguci** [comment]
????????????????/

**Comment by onsentawake** [comment]
この欄でふざけるのはちょっとダメですね、反省。
あくまで端的に（後から誰が見ても）わかるようにしないと、せっかくの機能も台無しになっちゃう。

しつれいしました～

**Comment by yuu-eguci** [comment]
そうだなあｗここをチャットみたいに使うと収集がつかなくなりますね…
