### ISSUE TITLE
「いらっしゃい。」の真下にマップが来たほうがいいかも。(スマホのとき【about3.html】

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#21]

**Comment by yuu-eguci** [comment]
これは about3.html のことですよね。タイトルに追加しておきます。

しかしこれは html 構造的にちょっとキツイです。どうしても、というわけでなければこのままにしたい。

**Comment by onsentawake** [comment]
難しいのであればぜひそのままで♪
では一旦クローズ

**Comment by yuu-eguci** [comment]
そうそう! Issue はこういう使いかたであってます > クローズ
