### ISSUE TITLE
ナビゲーションバーの表示を統一する

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#23]
ページによって文字の大きさがバラバラ。
これを整えたい

**Comment by yuu-eguci** [comment]
@onsentawake 
これに関連して、

- about3.html を正式な「Neo について」ページとし、他の about を削除。
- その他の、不要ページも削除。(もとの見本 alime は別途 zip で渡します。)
- index.html と sword.html のナビゲーションバーを about3.html のものと同じにする。

このへんやっていいですか？
index と sword については、もしいま Jiff がいじっているというなら、 conflict が面倒なので後回しでもいいです。

**Comment by onsentawake** [comment]
ぜひおねがいします
#5 がマージされたとして、pariyo#6のブランチまでは触ったと思うので、そこから料理していただけると嬉しいです！

**Comment by yuu-eguci** [comment]
よくわかりません。 `feature/#6_project924` からブランチを切るということですか？

**Comment by onsentawake** [comment]
その認識です！
今僕がいじっていて最終形態のものは`feature/#6_project924`になっています。

**Comment by yuu-eguci** [comment]
それは、あきまへん。
マージされていないブランチは問題だらけです。
そこからブランチを切ったら、問題はますます広がっていきます。
新しいブランチは、 master……もっとも問題のないブランチ……から切らないといけません。

**Comment by onsentawake** [comment]
EGCさんマスターからブランチ切る
JIFF　`feature/#6_project924`マージしてもらう
みたいなながれですか？

**Comment by yuu-eguci** [comment]
そうです。
なのでこの issue 用のブランチは、 master からぼくがこれから切ります。
Jiff は PR https://github.com/yuu-eguci/pari-yo-jana-924/pull/17 を、マージできる状態にしてください！
あるいは、ブランチが錯綜してめちゃくちゃになっている、とかでしたらまた master から切り直しても OK です。

**Comment by onsentawake** [comment]
了解です！！
`feature/#6_project924`に移動→masterのアップデート情報取得→作業開始
→完成したらプッシュ→PR　の流れでいいですか？

**Comment by yuu-eguci** [comment]
完璧！！
だけど conflict とか結構起こったら、ホント、 master から切り直していいですからね。

**Comment by onsentawake** [comment]
コンクリフトしたら失敗して学び、またおしえてもらいます

っていうか、マスターから今のブランチにアップデートしても両方のこっちゃう感じなんですか？

**Comment by yuu-eguci** [comment]
主語がよくわかりません。
両方とは何を意味していますか？

**Comment by onsentawake** [comment]
僕が今作業しているブランチをアップデートした際に、masterが変わっていたらGITHUBデスクトップで更新するとEGCさんの更新が反映されるとおもうんですけど、コンクリフトした場合は自分のローカルにもその部分が残るかんじですか？？

**Comment by yuu-eguci** [comment]
> コンクリフトした場合は自分のローカルにもその部分が残るかんじですか？？

このあたり、何がおっしゃりたいのかちょっと不明瞭なんです。
だけど「コンフリクトした場合、 Jiff のローカルに master のデータは残るのか」ということだとすれば yes です。

**Comment by onsentawake** [comment]
そうですそうです、コンクリフトした際にマスターと、今僕が作業しているものの両方がローカルにも残るのかなと思って
