### ISSUE TITLE
🤡 デザインをざくざく作っていく

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#3]
## 概要

alime テーマのテンプレートに上書きしていくかたちで、ざくざく 924 版サイトを作っていく。
担当: Jiff

@onsentawake GitHub に慣れるために、サイトに関する質問や議論は、この issue にコメントしていくかたちでしてみましょう！

**Comment by onsentawake** [comment]
調査中（もしよかったら教えてください）：

①TOPは２画面が循環して切り替わるが、それの構造？を知りたい
　→循環を止めたり、切替時間を変更したい
②CSSが多いのでまだ解析中
③いろいろブランチ切ってしまいましたが習うよりなれろ。。。
④h1見出しのタイトルをfadeにしたらおもしろかった

**Comment by yuu-eguci** [comment]
@onsentawake 
ざっくりと回答かきます。よかったらあとで通話しながら、これをもとに話しましょう。

> ①TOPは２画面が循環して切り替わるが、それの構造？を知りたい

```
index.html
    - Alime の index.html
    - Travelo の index.html
```

> ②CSSが多いのでまだ解析中

CSS を改造したいんですか? むつかしそうであれば、画像とかで実現したいイメージを提示してもらって、ぼくに投げてくれても OK です。

> ③いろいろブランチ切ってしまいましたが習うよりなれろ。。。

Git は意味不明だと思います。
ぼくが使ってもらっているものなので、何でも聞いてくれて OK です。
むしろ一度レクチャーしたほうがよさそうですね。
基本的には次のようにやります。

1. さあやるか、と思う。
1. ローカル環境の master ブランチを最新化する。(Fetch origin ボタンのこと)
1. ローカルで作業ブランチを切る。(`feature/[今から作るものの名前]` のような名称で)
1. 作る
1. コミットする。(`~~を追加` みたいなメッセージをつけて)
    - こないだのデザインモックの、ぼくのコミットメッセージを参考にしてください。これは英語ですけど。
    - https://github.com/yuu-eguci/TaskalAMS4Hekinan-mock/commits/master
1. Push する。
1. PR をする。
1. ぼくがレビューする。 OK なら master に取り込む。(マージというやつです)
1. Jiff はローカル環境の作業ブランチを消す。

繰り返しになりますが、デザインとか、写真とか、文章とかはともかく、 git やら css やら js で困ったことがあれば何でも聞いてください。

**Comment by onsentawake** [comment]
![image](https://user-images.githubusercontent.com/58753727/91190718-d964df80-e72e-11ea-8959-ae959cd61f8f.png)
![image](https://user-images.githubusercontent.com/58753727/91190755-e386de00-e72e-11ea-9255-b803144af74c.png)

**Comment by onsentawake** [comment]
![image](https://user-images.githubusercontent.com/58753727/91190785-eda8dc80-e72e-11ea-897d-643818b03eb5.png)

**Comment by onsentawake** [comment]
![image](https://user-images.githubusercontent.com/58753727/91192900-74f74f80-e731-11ea-985c-995dc9266844.png)

**Comment by yuu-eguci** [comment]
ほほ～進んでますねえ。でも Midori-tech ってなんや(見逃さんぞ)

**Comment by onsentawake** [comment]
・新着情報うめこみしたい（細かいこと調べる）
　　　　→なにかいいデザインないかなー枠ださいなー
・RSSについてもよく理解していないので調べる
・924さんから、標記はNeo,Sowrdがいいなぁというご意見いただき修正必要
・Swordページをざくざく作っていったので、同じレイアウトで各種ギターの説明ページをつくる

・Sword説明ページの下部 のh2　Line UPの色変えが上で宣言されているh2の設定と干渉してうまく変わらない

・各種ページのヘッダメニュー、リンク先コピーしなかん

・設計も、もっかい考えてみる

**Comment by onsentawake** [comment]
今日
ロゴ直す　完了
表記Sword　Neo　直す

**Comment by yuu-eguci** [comment]
ざくざく進めているみたいですね～。
RSS についてはぼくもよくわかってなかった頃に書いた記事があるんでシェアします。

https://www.mrrhp.com/ja/2016-04-20

**Comment by onsentawake** [comment]
しんじょうみゆ先生’のスクールは924サーバにあるファイルに直接仮でリンク張ってあるので、そのまま使うときは注意。
どちらにしろかきかえなければならないっ！

**Comment by yuu-eguci** [comment]
仮でってどういうことですか？

**Comment by onsentawake** [comment]
924さんの紹介ページつくるために取材
ギターの写真撮る
Sword
NICOICHI
ACOUSTIC
NeoSelect
Other　Mins
Goods　Parts
９２４さん作業風景
お店の外観撮る

**Comment by onsentawake** [comment]
Swordページの208行から下

 
                <div class="col-md-6 col-xl-3">
                    <div class="team-content-area text-center mb-30 wow fadeInUp" data-wow-delay="100ms">
                        <div class="member-thumb">
                            <img src="img/bg-img/sls.jpg" alt="">
                        </div>
                        <h5>SLS series</h5>
                        <span>Les Paul Type</span>
                        <div class="member-social-info">
                            <a href="https://www.facebook.com/kunishi.furuhashi.7"><i class="ti-facebook"></i></a>
                            <a href="#"><i class="ti-twitter-alt"></i></a>
                        </div>
                    </div>
                </div>


スマホブラウザ（クロームオペラ）で見るとレイアウト崩れる、、、

**Comment by yuu-eguci** [comment]
「ざくざく」期間は終了ということで、次からは小さな単位でつくっていきましょう。
この issue は close
