### ISSUE TITLE
🚀 引き渡し

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#30]

**Comment by yuu-eguci** [comment]
絵文字の使いかた、あってます！

**Comment by onsentawake** [comment]
デプロイ時には、924さんにカレーたかりにいきましょう

**Comment by yuu-eguci** [comment]
デプロイは #60 と #61 で行うので、この issue は引き渡しのみを対象とします。

**Comment by yuu-eguci** [comment]
> ９２４プロジェクト、一旦クローズでおねがいしまーす！
> くにしさんからだんにゃばーどいただきました！
> 写真の差し替えやちょっとしたｓｕｐｐｏｒｔは都度、イシュー開いて当面の間継続ってかんじです〜

ということで引き渡し完了とします。 Close!
