### ISSUE TITLE
✨ 各ページの JavaScript 処理の共通化

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#33]
## emoji 解説

✨: 機能追加の emoji

## 概要

まだ document.write で `Copyright © 2020` を描画しているページと、修正済みのページが混在しています。それをすべて共通化します。

**Comment by onsentawake** [comment]
これはコピペで対応できそうなので、後日JIFFやってみていいですか？
どうしようもなくなったら助けてほしいです。

**Comment by yuu-eguci** [comment]
あ、今回は JavaScript 系は Yuu やります!

**Comment by onsentawake** [comment]
オナシャス！！！DNBD
