### ISSUE TITLE
💄 「ネットでも購入できます」上下のスペース

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#34]
## emoji 解説

💄: デザイン関連の emoji

## 概要

上下のスペース、同じくらいにしときましょう。

![issue](https://user-images.githubusercontent.com/28250432/94540402-6563ad00-0281-11eb-8a85-e90358a7832e.png)

**Comment by onsentawake** [comment]
JIFFやってみます

**Comment by yuu-eguci** [comment]
よろしくお願いします!

- Branch: `feature/#34_top_design`
- Commits:
    - `#34 「ネットでも...」上下のスペース調整`
    - など

**Comment by yuu-eguci** [comment]
あとはこれをやれば、のこるは画像系だけですね!

**Comment by onsentawake** [comment]
![a](https://user-images.githubusercontent.com/58753727/95013435-3a130080-067b-11eb-8784-9127532d2c50.png)
![b](https://user-images.githubusercontent.com/58753727/95013437-3bdcc400-067b-11eb-970f-2294e8cbf159.png)


うーん一応無理やりできたけど、格好よくないのでもう少しなんかいい方法ないかなと考え中

問題点
・ネットでも。。。したの画像から。。。　についてはきちんとなっていて、その上側のハコ（col12？）がうまくいじれない

`vertical-align : middle;`　はうまくいかなかったです。

**Comment by onsentawake** [comment]
![d](https://user-images.githubusercontent.com/58753727/95018082-3b065b00-0698-11eb-97c0-4353a5efc419.png)
![c](https://user-images.githubusercontent.com/58753727/95018083-3cd01e80-0698-11eb-981b-de21ebd7a063.png)

とりあえずは納得のいく形
もっとかっこいい書き方はEGCさんに後からきくとして、一旦提出！

**Comment by yuu-eguci** [comment]
Closed by #54
