### ISSUE TITLE
💄 下部画像リンク J-Guiter と オーダーお問い合わせ の画像【保留中: Jiff が写真を調達する予定】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#35]
## emoji 解説

💄: デザイン関連の emoji

## 概要

600x300 の用意をお願いします!

![issue](https://user-images.githubusercontent.com/28250432/94540541-89bf8980-0281-11eb-8fb4-ebb41fe2db9f.png)

**Comment by onsentawake** [comment]
カメラMEN　NARI　と同行の上撮影のためお待ちください（一緒にNEOいって、インドカレーたべても◎

**Comment by yuu-eguci** [comment]
了解です。その旨タイトルに追記しときます。

**Comment by yuu-eguci** [comment]
- Branch: `feature/#35_link_photoes`
- Commits:
    - `#35 Studio STAIRWAY 画像追加`
    - `#35 しんじょうみゆ 画像追加`
    - など

**Comment by yuu-eguci** [comment]
各リンクの名称が変更されたので、 issue タイトルを変更します。

![issu](https://user-images.githubusercontent.com/28250432/94749617-29cefd00-03bf-11eb-8af5-30725cda7625.png)

**Comment by onsentawake** [comment]
つぎはこれ

**Comment by yuu-eguci** [comment]
よろしくお願いしまっす!

**Comment by yuu-eguci** [comment]
Closed by #67
