### ISSUE TITLE
🔥 右下の Facebook Twitter リンク削除

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#36]
## emoji 解説

🔥: 削除の emoji

## 概要

どうせ丸ボタンに隠れるので消しちゃいましょう。
あるいは隠れないように配置しましょう。

![issue](https://user-images.githubusercontent.com/28250432/94540677-b07dc000-0281-11eb-884a-9fe6674c6cab.png)

**Comment by onsentawake** [comment]
これ、やってみます

**Comment by yuu-eguci** [comment]
はーい。

- Branch: `feature/#36_sns_links`
- Commits:
    - `#36 フッタの Facebook Twitter リンク削除`
    - `#36 フッタの Facebook Twitter リンク位置調整`
    - など

こんなところですね。

**Comment by onsentawake** [comment]
しつもん！
SNSロゴを消したまではいいのですが、今度はNEOロゴがボタンにかぶっちゃいます
50pxほど上にあげても良いですか？

`<a href="#"><img src="img/core-img/logo7.gif" alt style="padding-bottom: 50px;"></a>`

**Comment by yuu-eguci** [comment]
現物を見てみないとわかりませんなあ。
画像をみせていただくか、あるいは Jiff が見て OK と思ったらそれでいいですよ!
最終チェックはレビューでするので〜

**Comment by yuu-eguci** [comment]
Closed by #47
