### ISSUE TITLE
🔥 スクロールにつれて要素がフェードインしてくるやつについて【ご提案】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#37]
## emoji 解説

🔥: 削除の emoji

## 概要

よかったらこれ消しません?
自分のポートフォリオサイトに使っていて、このフェードインの仕組みが良いと思ったことがないんです。
Issue はこういった相談の場としても使います。

**Comment by onsentawake** [comment]
おっと返信を飛ばしてました失礼。。。
けしましょ！　シンプルイズEGC!

もしよかったら、お願いします！

**Comment by yuu-eguci** [comment]
了解です! Yuu やります。
