### ISSUE TITLE
🐛 コンソールに出ている JavaScript エラー【sword.html】【acoustic.html】【neoselect.html】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#38]
## emoji 解説

🐛: 不具合の emoji

## 概要

【sword.html】【acoustic.html】【neoselect.html】について、画像に示すようにエラーが出ています。解消しましょう。

![issue](https://user-images.githubusercontent.com/28250432/94540827-e28f2200-0281-11eb-82b4-6c35b3af3829.png)

**Comment by onsentawake** [comment]
ありゃ、失礼しました。。。

一旦、お任せしても良いですか？

**Comment by yuu-eguci** [comment]
OK です!
Yuu 対応します。

**Comment by yuu-eguci** [comment]
確認したところ、これ、埋め込んだ YouTube から出てますね。
それはどうしようもないので無視しておきます。
それ以外にエラーはなかったので、この issue は解決ってことで! Close!
