### ISSUE TITLE
💄 Line Up エリアの問題【sword.html】【neoselect.html】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#39]
## emoji 解説

💄: デザイン関連の emoji

## 概要

画像に示すように、高さがズレています。
画像のサイズが違うためです。
および、 Facebook と Twitter のリンクがありますがこれは不要だと思います。

![issue](https://user-images.githubusercontent.com/28250432/94541079-21bd7300-0282-11eb-8cfa-d4a702ba0845.png)

**Comment by onsentawake** [comment]
これも写真差し替えたいので、サイズ指示お願いします。
アイコン削除もお願いしたいです

**Comment by yuu-eguci** [comment]
> サイズ指示お願いします。

オリジナルの画像サイズを Jiff のほうで見てもらって決めてください。

> アイコン削除もお願いしたいです

ということは、

1. Jiff が画像準備
1. ぼくが html 修正

ということでいいですかな？

**Comment by onsentawake** [comment]
はい、おねがいします！

**Comment by yuu-eguci** [comment]
わかりましたー。
じゃあ、こちらについてはぼくが仮画像で作っておくので、そのあとで実際の画像お願いします。
こちらから声かけるのでー。
