### ISSUE TITLE
🔥 下部カルーセルが残っています【sword.html】【acoustic.html】【neoselect.html】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#40]
## emoji 解説

🔥: 削除の emoji

## 概要

下部カルーセルは消すんですよね! 【sword.html】【acoustic.html】【neoselect.html】に残っています。

![issue](https://user-images.githubusercontent.com/28250432/94541266-57625c00-0282-11eb-9936-ba05ec8983d6.png)

**Comment by onsentawake** [comment]
消します。
消して、aboutと同じレイアウトにしたのち、リンク先をJギターとメールフォームに変えます。
JIFFやります

**Comment by yuu-eguci** [comment]
よろしくおねがいします!

- Branch: `feature/#40_remove_carousel`
- Commits:
    - `#40 各ページの下部カルーセル削除`
    - `#40 下部を about.html と同様に`
    - など

**Comment by onsentawake** [comment]
ふぉい！　やりまーす！

**Comment by yuu-eguci** [comment]
fixed by #53
