### ISSUE TITLE
💄 「ホーム」と「トップ」表記はそろえる

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#41]
## emoji 解説

💄: デザイン関連の emoji

## 概要

画像のとおり。「トップ」であわせましょう!

![issue](https://user-images.githubusercontent.com/28250432/94541385-7eb92900-0282-11eb-832b-174788f4d817.png)

**Comment by onsentawake** [comment]
JIFFやります！

**Comment by yuu-eguci** [comment]
OK! お願いします!

- Branch: `feature/#41_menu_text`
- Commits:
    - `#41 全ページの「ホーム」表記を「トップ」に修正`
    - など
    - (など、と書いてるのは、実際に手を付けるとほかのこともやることになるかもしれんからです!)

**Comment by onsentawake** [comment]
ほい！今からこれやります、ブランチも切っちゃうよ

**Comment by yuu-eguci** [comment]
fixed by #52
