### ISSUE TITLE
🐛 デザイン壊れてます【neoselect.html】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#42]
## emoji 解説

🐛: 不具合の emoji

## 概要

画像のとおり。

![issue](https://user-images.githubusercontent.com/28250432/94541484-9abcca80-0282-11eb-98fc-982867ca638b.png)

**Comment by onsentawake** [comment]
写真差し替えるYOTEIなので、もしよかったらサイズなどのアドバイスと修正をお願いしたいです

**Comment by yuu-eguci** [comment]
> 写真差し替えるYOTEI

ではそれでお願いします。

> サイズなどのアドバイス

以前申し上げたとおり、オリジナルと同じ画像サイズにすればいいです。

> と修正

どゆことですか？

**Comment by onsentawake** [comment]
あ、そうかオリジナルサイズに戻せばデザインもどるりますね
承知です、やります～

**Comment by yuu-eguci** [comment]
画像についてはそれで OK だと思います。

Html 崩れは、 Jiff のいつもの閉じタグ抜けじゃないかなと……ｗ あるいはそれに類するミスでないかなと思います。
よくわかんなくなっちゃったら Yuu やります。

**Comment by yuu-eguci** [comment]
- Branch: `feature/#42_design_fix_neoselect`
- Commits:
    - `#42 [実際どんな異常かわかんないので、その具体的な内容を]`

**Comment by yuu-eguci** [comment]
担当者変更: Jiff -> Yuu
