### ISSUE TITLE
💄 Neo について の画像

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#43]
## emoji 解説

💄: デザイン関連の emoji

## 概要

960x300 と 600x431 の画像をお願いします!

![issue](https://user-images.githubusercontent.com/28250432/94541581-b58f3f00-0282-11eb-9dd3-4ffc1a5bebc8.png)

**Comment by onsentawake** [comment]
CAMERA　MEN　NARI　と同行の元実施予定

**Comment by yuu-eguci** [comment]
のちに写真を調達する予定、ということですよね？
ではその旨、タイトルに書いておきます。
こうすることで issue 一覧でわかりやすいのです。

**Comment by yuu-eguci** [comment]
あ、忘れてた。

- Branch: `feature/#43_about_photoes`
- Commits:
    - `#43 about.html に写真追加`
    - など

**Comment by onsentawake** [comment]
YARU

**Comment by yuu-eguci** [comment]
Fixed by #70
