### ISSUE TITLE
💄 フッタの統一

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#48]
## emoji 解説

💄: デザイン関連の emoji

## 概要

![issue](https://user-images.githubusercontent.com/28250432/94637084-9e4b6280-0311-11eb-91ce-d2a67aede364.png)

**Comment by onsentawake** [comment]
左の画像のフッターがかっこいいのでそれにしたいです
ちょっと甘えてEGCさんおねがいできますか？

**Comment by yuu-eguci** [comment]
はーいおまかせを!

**Comment by onsentawake** [comment]
かっこいいいいDNBD
