### ISSUE TITLE
💄 Line Up エリアの画像【sword.html】【neoselect.html】

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#49]
## emoji 解説

💄: デザイン関連の emoji

## 概要

- [💄 Line Up エリアの問題【sword.html】【neoselect.html】を解消 #44](https://github.com/yuu-eguci/pari-yo-jana-924/pull/44)

この PR により、 Line Up エリアのがたがたを修正し、サンプル画像を埋め込んでおきました。
こちらの実際の画像をお願いします!

**Comment by onsentawake** [comment]
わーいDNBD!

**Comment by yuu-eguci** [comment]
はーいあとよろしくです!

**Comment by yuu-eguci** [comment]
@onsentawake 
他の画像系 issues には必要な画像サイズを記述しているので、こちらの issue にも補足。

![issue](https://user-images.githubusercontent.com/28250432/95065868-95f18e00-073c-11eb-9c32-a14328e9d218.png)

200x200 を3種類ですね。

**Comment by onsentawake** [comment]
よおおおおしやるぞおおおおお(あした）

**Comment by yuu-eguci** [comment]
お願いします。

**Comment by yuu-eguci** [comment]
Fixed by #64
