### ISSUE TITLE
💄 ページタイトルの形式をあわせましょう

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#55]
全部こうする。

```
[ページ名] - Guitar Shop Neo
```

**Comment by yuu-eguci** [comment]
@onsentawake 
これは Jiff お願いしまーす!

**Comment by onsentawake** [comment]
はーい！　あわせまーす

**Comment by onsentawake** [comment]
ブランチ名、まだ記載されてないから試しに

feature/#55_page-title 

これで良きですか？

**Comment by yuu-eguci** [comment]
あっ忘れてた。
ブランチ名、完璧です！！コミットメッセージは提供します。

- `#55 ページタイトルの形式を統一`

もうひとつの issue のほうは、ブランチ名もコミットメッセージも、両方 Jiff が作ってください！

**Comment by yuu-eguci** [comment]
Closed by #57
