### ISSUE TITLE
✨ 外部サイトへのリンクは別タブで開きましょう

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#56]
このリンク↓で、外部リンクは別タブで開いていますよね。

![issue](https://user-images.githubusercontent.com/28250432/94540541-89bf8980-0281-11eb-8fb4-ebb41fe2db9f.png)

ヘッダの j-guitar へのリンク↓を始めとした、外部サイトへのリンクは別タブで開くよう統一しちゃいましょう。

![issue](https://user-images.githubusercontent.com/28250432/95066179-fed90600-073c-11eb-8902-ae499553f239.png)

ヘッダだけじゃないですから、気をつけて!

**Comment by yuu-eguci** [comment]
@onsentawake 
Jiff お願いします!

**Comment by onsentawake** [comment]
今日これやります

**Comment by yuu-eguci** [comment]
Closed by #58
