### ISSUE TITLE
🔥 使われていない画像の削除

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/pari-yo-jana-924#65]
## emoji 解説

🔥: 削除の emoji

## 概要

@onsentawake 使われていない画像、消してください! あやまってページに使われている画像を消さないよう、

1. 消そうと思っている画像の名前をコピー
1. vscode の grep 検索でその画像名が html に使われていないことを確認

しながら消すことをおすすめします!

**Comment by onsentawake** [comment]
わーい久しぶりのissue！！
やり方もありがとうございます！！！

新しい画像増やす前にコレやります

**Comment by yuu-eguci** [comment]
Fixed by #66
