### ISSUE TITLE
💄swordの紹介文ちょっと修正

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#73]
924さんより修正依頼
【Neo Select ページ】
・Sword と Tokai が混同して不快
→Tokaiとも関係が深く・・・などに変える
・材料の紹介もシンプルに書き換えてほしい
→明言せず、厳選された素材などに変更
・LS200の文言、軽自動車の文言を削除する

**Comment by yuu-eguci** [comment]
@onsentawake 
ブランチ名

- `feature/#73_924_requests`

**Comment by yuu-eguci** [comment]
Closed by #74
