### ISSUE TITLE
💄Swordの紹介文修正2

### ISSUE THREAD

**Issue by onsentawake** [yuu-eguci/pari-yo-jana-924#75]
20210127
924さんよりお願いあり

**Neo Select**

TOKAI　Neo　Select　とは　TOKAIと言えば　古くから　いわゆる　Vintage　TYPEモデルの名機を沢山生み出してきたブランドです　近年多様化も進み　様々な要求に　応えるために　オーダーメイドギターや少量生産の　楽器が　求められる時代へ　そんな中で　最良の楽器とは何かを　追求する過程でNeoの提案する　理想の形を　当社のアイデアで　生み出される　それが　Neoセレクトです・

Body＆Neckは　マテリアルにしていただき　世界の名機のディテールを生かし最新技術で　そのサウンドのテイストを
今の時代に　マッチした形で　再現する　その外観上の　マテリアルのこだわりも　Neo流　にアレンジ　その世界観を　表現者（アーチスト）にリスペクトできるように　Neo独自のオリジナルパーツなどで　構成されています

サウンド　多くのかつてのミュージシャンが　活躍していた時代を　シュミレーションし　そのサウンドが　小さなアンプでも　再現できるよう　サウンドイメージを　ピックアップ　POT　キャパシター　中の配線材など　細かな部分の組み合わせで　高いレベルで構築されております

Swordとは　一味違う　サウンドをお楽しみいただけます

**Swordの紹介**

Swordとは　ヴィンテージの名機たち　そのサウンドは　あまりに印象が　強く　そのサウンドを探し求めるためには　当時のものを購入するしかない　しかしながら　そのサウンドのイメージが　しっかり　データー化されれば　そのサウンドの片鱗に近づけるのではないか　少々　切り口としては化学的な感は否めない　しかし　材料を同じようなモノを探せればある程度は近いモノができると　考える事はできても　探すのは容易ではありません　材料を質や質量　音の伝達など　それらを調べていくうちに　まず　材料が良いこと　値段ではなく質が良いこと　楽器に何が重要か　弾きやすさやその他目指している音など　一つの到達点の回答が　Swordであり　その切れ味は　弾き手を剣客に見立てて　弾きやすさと音の良さ　これを提案したギター　最高の品質　も　弾く人の側にありたい　それが　Swordです・・

**塗装の件**　美しい塗装は　経験豊かなクラフトマンたちによって行われ　その美しさは　世界レベルです・・

**パーツ**　基本的には企業秘密

パーツはギターやそれぞれの音に対して　厳選し　サウンドメイキング技術で　かつてのアーチストたちの　音を　ディフォルメし　それを具現化することで　高いレベルの　音作りに貢献　表現者（アーチスト）を熱くさせる　何かを感じていただけると思います・・

**Comment by yuu-eguci** [comment]
@onsentawake 
ブランチ名: `feature/#75_924_requests`

**Comment by yuu-eguci** [comment]
Closed by #76
